package:
  name: pm_tb_data
  version: "0.1.0"

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: python -m pip install . --no-deps -vv
  preserve_egg_dir: True
  noarch: python

requirements:
  build:
    - python ~=3.10.0

  run:
    - python ~=3.10.0
    - earthaccess ~=0.6.1
    - numpy ~=1.22.4
    - xarray ~=2023.6
    - netCDF4 ~=1.6.3
    - rasterio ~=1.3.6
    - loguru ~=0.7

about:
  home: https://github.com/nsidc/pm_tb_data
  license: MIT
  summary: code for accessing passive microwave brightness temperature data in a consistent manner.

test:
  imports:
    - pm_tb_data
