package:
  name: pm_tb_data
  version: "0.6.1"

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: python -m pip install . --no-deps -vv
  preserve_egg_dir: True
  noarch: python

requirements:
  build:
    - python ~=3.10.0

  run:
    - python ~=3.10.0
    - earthaccess ~=0.14.0
    - numpy >=2.2.6
    - xarray >=2025.6.1
    - netCDF4 >=1.7.2
    - rasterio >=1.4.3
    - loguru >=0.7.3
    - h5py >=3.14.0
    - h5netcdf >=1.6.4

about:
  home: https://github.com/nsidc/pm_tb_data
  license: MIT
  summary: code for accessing passive microwave brightness temperature data in a consistent manner.

test:
  imports:
    - pm_tb_data
    - pm_tb_data.fetch
