name: pm_tb_data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - earthaccess ~=0.6.1
  - numpy ~=1.22.4
  - xarray ~=2023.6
  - netCDF4 ~=1.6.3
  - rasterio ~=1.3.6
  - loguru ~=0.7

  #############################
  # Non-imported dependencies #
  #############################

  # testing/linting/typechecking
  - pre-commit
  - pytest ~=7.1
  - mypy

  # Bulid utilities
  - conda-build ~=3.25.0
  - boa ~=0.15.1

  # other utilities
  - bump-my-version ~=0.10.0
  - ipython
  - ipdb
  - conda-lock
