name: pm_data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - earthaccess

  #############################
  # Non-imported dependencies #
  #############################

  # linting
  - pre-commit

  # other utilities
  - ipython
  - ipdb
  - conda-lock
