name: pm_tb_data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.0

  ########################################
  # Imported dependencies and extensions #
  ########################################
  - earthaccess ~=0.14.0
  - numpy >=2.2.6
  - xarray  >=2025.6.1
  - netCDF4 >=1.7.2
  - rasterio >=1.4.3
  - loguru >=0.7.3
  - h5py >=3.14.0
  - h5netcdf >=1.6.4

  #############################
  # Non-imported dependencies #
  #############################

  # testing/linting/typechecking
  - pre-commit
  - pytest
  - pytest-cov
  - mypy
  - pyfakefs

  # Bulid utilities
  - conda-build
  - boa
  - anaconda-client

  # other utilities
  - bump-my-version
  - ipython
  - ipdb
  - conda-lock
  - invoke
